In [1]:
import numpy as np
arr1=np.array([1,3,6,7,8,9])
print(arr1)

[1 3 6 7 8 9]


In [2]:
arr2=np.array([[1,2,3,4],[6,7,8,9]])
print(arr2)

[[1 2 3 4]
 [6 7 8 9]]


In [6]:
Zeros_arr=np.zeros((3,2))
print(Zeros_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
arr3=np.array([1,2,3,4],dtype=np.float32)
arr4=np.array([1,2,3,4,],dtype=np.int32)
print(arr3,arr3.dtype)
print(arr4.dtype)

[1. 2. 3. 4.] float32
int32


In [14]:
n_arr3=arr3.astype('i')
print(arr3,arr3.dtype)
print(n_arr3,n_arr3.dtype)

[1. 2. 3. 4.] float32
[1 2 3 4] int32


In [17]:
arr5=np.arange(10)
print(arr5,arr5.dtype)
n_arr5=arr5.astype('f')
print(n_arr5,n_arr5.dtype)

[0 1 2 3 4 5 6 7 8 9] int32
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float32


In [18]:
str_arr=np.array(['hema','priya','yogasri'])
print(str_arr)

['hema' 'priya' 'yogasri']


In [23]:
a=np.array([1,3,5,7,6])
c=a.astype('f')
b=np.array([2,4,6,8,9])
print(c+b)
print(c-b)
print(c*b)
print(c%b)
print(c/b)
print(c//b)
print(c**b)

[ 3.  7. 11. 15. 15.]
[-1. -1. -1. -1. -3.]
[ 2. 12. 30. 56. 54.]
[1. 3. 5. 7. 6.]
[0.5        0.75       0.83333333 0.875      0.66666667]
[0. 0. 0. 0. 0.]
[1.0000000e+00 8.1000000e+01 1.5625000e+04 5.7648010e+06 1.0077696e+07]


In [30]:
arr6=np.arange(12)
newarr=arr6.reshape(3,4)
print(newarr)
print("Fortran order ")
newarr1=arr6.reshape((3,4),order='F')
print(newarr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Fortran order 
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [32]:
arr7 = np.array([[1, 2], [3, 4]])
arr8 = np.array([[2, 1], [3, 5]])
greater_than=arr7>arr8
less_than=arr7<arr8
equal_to=arr7==arr8
print("greater than:\n",greater_than)


greater than:
 [[False  True]
 [False False]]


In [33]:
print("lesser than:\n",less_than)

lesser than:
 [[ True False]
 [False  True]]


In [34]:
print("Equal to:\n",equal_to)

Equal to:
 [[False False]
 [ True False]]


In [41]:
x = np.arange(12)
print("x=",x)

x= [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
print("x= ",x[:5])

x=  [0 1 2 3 4]


In [44]:
print("x= ",x[5:])

x=  [ 5  6  7  8  9 10 11]


In [43]:
print("x= ",x[::2])

x=  [ 0  2  4  6  8 10]


In [42]:
print("x= ",x[::-1])

x=  [11 10  9  8  7  6  5  4  3  2  1  0]


In [46]:
x2 = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [47]:
print(x2[:2,:3])

[[12  5  2]
 [ 7  6  8]]


In [48]:
print(x2[:2,::3])

[[12  4]
 [ 7  8]]


In [49]:
print(x2[::-1])

[[ 1  6  7  7]
 [ 7  6  8  8]
 [12  5  2  4]]


In [52]:
b=newarr>5
print(b)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [54]:
print(newarr[b])

[ 6  7  8  9 10 11]


In [55]:
newarr[b]=1
print(newarr)

[[0 1 2 3]
 [4 5 1 1]
 [1 1 1 1]]


In [56]:
print(newarr.T)

[[0 4 1]
 [1 5 1]
 [2 1 1]
 [3 1 1]]


In [57]:
print(np.transpose(newarr))

[[0 4 1]
 [1 5 1]
 [2 1 1]
 [3 1 1]]


In [59]:
t_newarr=newarr.T
print(t_newarr)

[[0 4 1]
 [1 5 1]
 [2 1 1]
 [3 1 1]]


In [60]:
print(np.dot(newarr,t_newarr))

[[14 10  6]
 [10 43 11]
 [ 6 11  4]]


In [63]:
narr2=np.arange(12)
n2=narr2.reshape(3,4)
print(np.multiply(newarr,n2))

[[ 0  1  4  9]
 [16 25  6  7]
 [ 8  9 10 11]]
